name = "iris"
srcDir = "./src/"
defaultTargets = ["Iris", "IrisTest"]

[[require]]
name = "aeneas"
path = "../aeneas/backends/lean/"

[[require]]
name = "Qq"
scope = "leanprover-community"
version = "git#stable"

[[lean_lib]]
name = "Iris"

[[lean_lib]]
name = "IrisTest"
globs = ["Iris.*"]
